//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenesixInv.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenesixInv.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interno.
        /// </summary>
        internal static string codInterno {
            get {
                return ResourceManager.GetString("codInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código PLU.
        /// </summary>
        internal static string codPlu {
            get {
                return ResourceManager.GetString("codPlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        internal static string eanArticulo {
            get {
                return ResourceManager.GetString("eanArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad incorrecta.
        /// </summary>
        internal static string ErrorCantidad {
            get {
                return ResourceManager.GetString("ErrorCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plu no encontrado.
        /// </summary>
        internal static string ErrorPlu {
            get {
                return ResourceManager.GetString("ErrorPlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda incorrecta.
        /// </summary>
        internal static string ErrorTienda {
            get {
                return ResourceManager.GetString("ErrorTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona incorrecta.
        /// </summary>
        internal static string ErrorZona {
            get {
                return ResourceManager.GetString("ErrorZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo 1.
        /// </summary>
        internal static string Grupo1 {
            get {
                return ResourceManager.GetString("Grupo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo 2.
        /// </summary>
        internal static string Grupo2 {
            get {
                return ResourceManager.GetString("Grupo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        internal static string Tienda {
            get {
                return ResourceManager.GetString("Tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uni.Paquete.
        /// </summary>
        internal static string uniPaq {
            get {
                return ResourceManager.GetString("uniPaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        internal static string Zona {
            get {
                return ResourceManager.GetString("Zona", resourceCulture);
            }
        }
    }
}
